@echo off
del "tools\MTK"
del "tools\STD"
rmdir /s /q %~N1
chcp 1251
if (%1)==() (
	echo Select image
		goto DONE
)
setlocal enabledelayedexpansion
rem находим смещение kernel 
"tools\sfk166.exe" hexfind %1 -pat -bin /88168858/ -case >tools\offset.txt
rem находим смещение ram_disk.gz
"tools\sfk166.exe" hexfind %1 -pat -bin /FFFFFFFF1F8B08/ -case >>tools\offset.txt
rem очищаем результаты поиска
"tools\sfk166.exe" find tools\offset.txt -pat offset>tools\off2.txt
"tools\sfk166.exe" replace tools\off2.txt -binary /20/0A/ -yes
if exist %~N1 rd /s /q %~N1 >nul
set /A N=0

:loop
FOR /F %%G IN (tools\off2.txt) DO (
	if !N!==1 (
		set /A ofs1=%%G
		set /A N+=1
	)
	if !N!==3 (
		set /A ofs2=%%G
		set /A N+=1
	)
	if !N!==5 (
		set /A ofs3=%%G+4
		set /A N+=1
	)	
	if `%%G` EQU `offset` (
		set /A N+=1
	)
)
FOR %%i IN (%1) DO ( set /A boot_size=%%~Zi )
del tools\offset.txt
del tools\off2.txt
md %~N1
"tools\sfk166.exe" partcopy %1 -fromto 0x0 %ofs1% %~N1\kernel_header -yes
"tools\sfk166.exe" partcopy %1 -fromto %ofs1% %ofs2% %~N1\kernel -yes
"tools\sfk166.exe" partcopy %1 -fromto %ofs2% %ofs3% %~N1\ram_header -yes
"tools\sfk166.exe" partcopy %1 -fromto %ofs3% %boot_size% %~N1\ram_disk.gz -yes
"tools\7z.exe" -tgzip x -y %~N1\ram_disk.gz -o%~N1 >nul
md %~N1\rmdisk
cd %~N1
cd rmdisk
"tools\cpio.exe" -i <../ram_disk
cd ..
cd ..
copy %1 %~N1 >nul
echo AUTOGENERATED >> tools/MTK

if exist %~N1/rmdisk/default.prop goto END
rmdir /s /q %~N1
del "tools\MTK"
del size.txt >nul
del tmp1.dat>nul
del 1.part*>nul

chcp 1251
if (%1)==() (
	echo Need an img file to proceed...
		goto end
)
setlocal enabledelayedexpansion
"tools\sfk166.exe" hexfind %1 -pat -bin /000000000000A0E10000A0E1/ -case >tools\offset.txt
"tools\sfk166.exe" hexfind %1 -pat -bin /000000001F8B08/ -case >>tools\offset.txt 
"tools\sfk166.exe" find tools\offset.txt -pat offset>tools\off2.txt
"tools\sfk166.exe" replace tools\off2.txt -binary /20/0A/ -yes
if exist %~N1 rd /s /q %~N1 >nul
set /A N=0

:loop
FOR /F %%G IN (tools\off2.txt) DO (
	if !N!==1 (
		set /A ofs1=%%G
		set /A N+=1
	)
	if !N!==3 (
		set /A ofs2=%%G
		set /A N+=1
	)
	if !N!==5 (
		set /A ofs3=%%G+4
		set /A N+=1
	)	
	if `%%G` EQU `offset` (
		set /A N+=1
	)
)
FOR %%i IN (%1) DO ( set /A boot_size=%%~Zi )
set /A real_ofs=%ofs2%+4
md %~N1
set /A ps=%ofs1%+4
echo %ps%>%~N1\pagesize.txt
set /A ps=%ofs1%+4
del tools\offset.txt
del tools\off2.txt
"tools\sfk166.exe" partcopy %1 -fromto %ps% %real_ofs% %~N1\kernel -yes
"tools\sfk166.exe" partcopy %1 -fromto %real_ofs% %boot_size% %~N1\ram_disk.gz -yes
"tools\7z.exe" -tgzip x -y %~N1\ram_disk.gz -o%~N1 >nul
md %~N1\rmdisk
cd %~N1
cd rmdisk
%current%/tools/cpio.exe -i <../ram_disk
cd ..
cd ..
copy %1 %~N1  >nul 
echo AUTOGENERATED >> tools/STD
if exist %~N1/rmdisk/default.prop goto END>nul
if not exist %~N1/rmdisk/default.prop goto FAIL>nul

:FAIL
"tools/cecho" {0C}FAILED{#} 
pause
goto END

:END