#!/sbin/sh
#AUTOGENERATED BY THE RICKY310711 WINDOWS ROM KICTHEN

cd /data/app
for f in $(ls *.apk) 
do
	rm /tmp/SDBUPPS/$f
done
mkdir /data/app
cd /
cd /tmp/SDBUPPS
for f in $(ls *.apk) 
do
	cp $f /data/app/
	chmod 644 /data/app/$f
done
cd /
rm -r /tmp/SDBUPPS

#Exit
exit

#By Ricky310711
#Copyright SPRTools ditributed under the GNU GPL